feat(core): add the ability to forward arguments to dotnet new
nx-dotnet/nx-dotnet pull request #584
Opened 2023-01-02 23:37 UTC by balloman

This PR adds the ability to forward arguments to the `dotnet new` command.

This can be done with either the `--args` parameter or by appending to the end of the generate command with `--`.

This method could also be applied for any situation where it would be beneficial to forward arguments to the invoked command

Fixes: #262 , #398

2023-01-04 15:12 UTC, AgentEnder requested changes
Hey, thanks for the PR! 🎉 

Can you add an e2e test for this?

2023-01-04 15:12 UTC, AgentEnder commented on packages/core/src/generators/app/schema.json
> +    "_": {
Lets also rename this to be a bit longer. Something like `__unparsed__` would work, similar to the prop name in the run-commands schema.

2023-01-05 01:54 UTC, balloman commented on packages/core/src/generators/app/schema.json
> +    "_": {
Yeah, the goal was to keep the name the same as it is in the options object. I think there is a way to add code to copy the "_" property to the "__unparsed__" property, but I left it alone for consistency. Thoughts?

2023-01-05 03:11 UTC, balloman commented
> Hey, thanks for the PR! 🎉
> 
> Can you add an e2e test for this?

I'm not completely sure how to go about adding and e2e test specifically for argument forwarding. Seems that "--" gets interpreted by yarn every time

2023-01-13 23:46 UTC, AgentEnder commented
I'll look into this more at some point this weekend and see if I can't figure out why its not letting you pass them.

2023-02-09 16:18 UTC, nslusher-sf commented
@balloman @AgentEnder I created a PR to add an e2e test for the --args feature [here](https://github.com/balloman/nx-dotnet/pull/1).

As balloman stated if you run the command with "--" with yarn it will not pass through properly to the generator `yarn nx generate @nx-dotnet/core:app ${app} --language="C#" --template="webapi" -- --exclude-launch-settings=true`. 

However if you run it without yarn it does work: `nx generate @nx-dotnet/core:app ${app} --language="C#" --template="webapi" -- --exclude-launch-settings=true`

With that being said if the e2e test for --args was added to this PR would it be good to merge with the caveat that the other "--" feature will not work when using yarn? It would be nice to have this feature merged in - we would definitely use it.

2023-04-18 14:27 UTC, nslusher-sf commented
@AgentEnder Any updates on this PR?

2023-05-01 00:08 UTC, balloman commented
> Lets get this merged, sorry for dropping the ball a bit. Its picked up some conflicts and I have some small feedback left.
> 
> Can you get to it @balloman? If not, I'll update the PR when I get time but that will be a week or so in all likelihood.

I don't use this software anymore, but I can try to take a look into it

2023-05-01 19:31 UTC, balloman commented
> Lets get this merged, sorry for dropping the ball a bit. Its picked up some conflicts and I have some small feedback left.
> 
> Can you get to it @balloman? If not, I'll update the PR when I get time but that will be a week or so in all likelihood.

I haven't been able to figure out a way to make the changes requested to the pr and still keep the double dash functionality (--). Unless the schema is exactly the way it is above, then it doesn't pass. My knowledge of how the nx argument passing works is quite limited, however, and as you can see, I haven't really had time to come back to this PR

2023-05-23 11:59 UTC, Soulusions commented
I've made the requested changes on my own fork https://github.com/Soulusions/nx-dotnet/commit/354b6e65b0a46c3aeec7057bb08944b1bc9466c9, don't know if this is the best course of action since I don't have write permissions to the PR, though I hope this helps move the merge forward!!

2023-05-30 17:03 UTC, balloman commented
> Hey @balloman, I made a PR with the changes on your fork, would love if you could check it out 🫡

Ultimately, like I noted earlier, the changes themselves are relatively trivial, you just lose the "--" functionality. So you can only pass arguments using "-args=". I don't know how much of a deal this is to be honest, but at this point, it would probably be easier to just make a new PR. I decided against using nx-dotnet many months ago.

2023-05-31 11:10 UTC, Soulusions commented
Thanks for the reply!
I moved this to #722

2023-09-20 03:42 UTC, AgentEnder commented
Closing this out at @Soulusions PR was merged.

2023-09-20 03:42 UTC, closed without merging